### PR TITLE
DHFR-gas works; separate list of improper and proper periodic torsion

### PR DESCRIPTION
**Pull request by leeping**
Hi Jason,

I got gas phase DHFR to work, which I think is a small milestone. :) Some parameters weren't being assigned; after adding them, I got some more errors from improper periodic torsion parameters (function type 4) being incorrectly assigned to proper periodic torsions (function type 9).  I tried several solutions and the most straightforward one was to maintain a separate list of `improper_periodic_types` by subclassing `ParameterSet`.  Let me know if this is an acceptable solution.

Before:

```
Traceback (most recent call last):
  File "../test.py", line 77, in <module>
    system = ParmEd_GmxTop.createSystem(nonbondedMethod=app.NoCutoff,constraints=omm_constraints,rigidWater='FLEXIBLE' not in defines)
  File "/home/leeping/local/lib/python2.7/site-packages/chemistry/structure.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "/home/leeping/local/lib/python2.7/site-packages/chemistry/structure.py", line 1563, in createSystem
    self._add_force_to_system(system, self.omm_dihedral_force())
  File "/home/leeping/local/lib/python2.7/site-packages/chemistry/structure.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "/home/leeping/local/lib/python2.7/site-packages/chemistry/structure.py", line 1839, in omm_dihedral_force
    raise MissingParameter('Cannot find torsion parameters')
chemistry.exceptions.MissingParameter: Cannot find torsion parameters
```

After:

```
#========================================================#
#|              GROMACS energy components               |#
#========================================================#
Bond                      [ 67.912148]
Angle                     [ 3737.411681]
Proper-Dih.               [ 6989.859875]
Improper-Dih.             [ 287.95874]
LJ-14                     [ 2668.137351]
Coulomb-14                [ 28993.910139]
LJ-(SR)                   [-4396.359132]
Coulomb-(SR)              [-38099.888625]
Potential                 [ 248.942177]
----------------------------------------------------------
#========================================================#
#|         OpenMM energy components via ParmEd          |#
#========================================================#
HarmonicBondForce         67.9121481797
HarmonicAngleForce        3737.4116813
PeriodicTorsionForce      7277.81861466
NonbondedForce            -10834.200713
CMMotionRemover           0.0
Potential                 248.941731172
----------------------------------------------------------
Energy Difference (kJ/mol):
-0.000445827948255
RMS Force Difference (kJ/mol/nm):
2.43198247766e-05
```

Thanks,
- Lee-Ping

### CODE REVIEW

**Comment by swails** [comment]
> I tried several solutions and the most straightforward one was to maintain a separate list of `improper_periodic_types` by subclassing `ParameterSet`. Let me know if this is an acceptable solution.

Oh I never even though about this!  Improper torsions are handled and assigned differently than proper torsions, so they definitely need a separate type list in the `ParameterSet`.  There really is no use-case for grouping the types in the same list inside `ParameterSet`, and following the Python mantra "flat is better than nested", the best thing to do here is to just add that list to the underlying `ParameterSet` object itself (no need to subclass here).  In light of the fact that you had no way of knowing that I didn't take advantage of having them in the same list before, your solution was the best one.  I'll merge this and fix it myself.

BTW -- can you add a test case in a separate PR (preferably one that doesn't depend on `ForceBalance` to make it easier to run in Travis-CI)?  It will make it easier for me to make sure I don't accidentally undo any of your changes...

Thanks again for all your work on this!

**Comment by leeping** [comment]
Sure, I'd be happy to make my test script independent of ForceBalance. There will still be dependence on Gromacs and OpenMM; is that okay?
- Lee-Ping

**Comment by swails** [comment]
Also, can you give me an example of this "variable precision" GRO file?  I wrote the GRO parser based on the format spec outlined in the Gromacs manual, but realized that the fixed-width format would be quite limiting for any system >=100K atoms.

**Comment by swails** [comment]
> Sure, I'd be happy to make my test script independent of ForceBalance. There will still be dependence on Gromacs and OpenMM; is that okay?

Definitely.  The test suite already depends on both Gromacs and OpenMM (the former installed via apt-get and the latter installed via conda in the Travis install script, [here](https://github.com/ParmEd/ParmEd/blob/gromacs_support/devtools/travis-ci/install.sh#L2-L19)

**Comment by swails** [comment]
As for the variable precision GRO -- if you just add one to the test suite in another PR, I'll add a test for it to make sure that format detection and parsing are both done correctly.

**Comment by leeping** [comment]
Sure - here's an example:  https://dl.dropboxusercontent.com/u/5381783/conf.gro

The documentation for the .gro file format says: "This format is fixed, ie. all columns are in a fixed position. Optionally (for now only yet with trjconv) you can write gro files with any number of decimal places, the format will then be n+5 positions with n decimal places (n+1 for velocities) in stead of 8 with 3 (with 4 for velocities). Upon reading, the precision will be inferred from the distance between the decimal points (which will be n+5)."  

I'll include a similar example in the forthcoming PR.
- Lee-Ping

**Comment by leeping** [comment]
Instead I should thank you for developing this tool.  Reading through it, I can tell it's thoughtfully designed and I'm sure it will be very useful for lots of research in the future.  :)

**Pull request merged**
