### PR TITLE
Added test systems for Gromacs support

### PR DESCRIPTION
**Pull request by leeping**
This PR adds a bunch of tests in `GmxTests`.  The layout is fairly simple, but it's not standardized to the framework in ParmEd.  Let me know if I can provide further help integrating it.

`test.py` is now independent of ForceBalance so it should work with your Travis-CI.

I used Gromacs 4.6.5 to do the tests.  Hopefully the results stay the same with newer versions of Gromacs :)

```
- About.txt (simple description)
- test.py (main testing script)
- nifty.py (ForceBalance convenience functions, standalone file)
- molecule.py (useful for writing output .gro files from OpenMM, but not needed for test)
- 01.1water
  |- conf.gro
  |- topol.top
  |- shot.mdp
  |- (itp files and force field folders)
  |- command.sh (one-liner for running test.py)
- (other test folders)
```

### CODE REVIEW

**Comment by leeping** [comment]
One thing: `nifty.py` is needed to run the tests, as long as it's in the same folder as `test.py` it should work.

**Comment by swails** [comment]
Awesome, thanks.  I'll try to get these worked into the main test suite (at least some of them -- the Travis tests are already ~20 minutes, so I have to start looking into ways of cutting down the length of some of these tests).

Just a quick question -- are any of the files you added here part of the standard Gromacs distribution?  If so, can we get rid of them and just use the ones from Gromacs?  Or is this not the case?

**Comment by leeping** [comment]
The `amberxx.ff` folders (two deep) are from the standard Gromacs distribution - I think that's it.  If ParmEd and the external Gromacs calls know about GMXLIB, then I don't think the `amberxx.ff` folders are necessary.  I didn't know how to pass the path to ParmEd.

These tests presently take about 5 minutes to run on my workstation, and most of it is DHFR.  I suggest paring things down to, say, 04 (alanine dipeptide gas phase), 08 (water box PME), and 10 (DHFR PME Switch) to reduce runtime.

**Comment by swails** [comment]
Holy cow @leeping -- do you ever sleep? :)

I've been running your tests, and you're right -- they don't take too long.  The only thing I really want for the CI testing is to make sure that the overall energies don't change as we work on the code, so I'm not worried about running Gromacs (and Travis uses the CPU platform, which is a lot faster than Reference).  I've been preparing the tests in my `lpgmx` branch (the one I issued a PR into your fork from) taken from your `GmxTests` directory (and omitting the `amberxx.ff` directories, as those are part of the standard install as you said).  I chose 01, 02, 03, 07, and 09.  I'll push those changes to my PR shortly.

**Comment by leeping** [comment]
I did sleep - there is a gap of 6-7 hours between my two comments :)

Are you sure you'd rather use 9 over 10?  10 is a bit closer to what we might do in a "production" environment.  

Also, I don't think 03 contains any improper dihedrals; I built that system by hand some time ago and I don't think it's a correct reproduction of the AMBER force field.  I only have improper dihedrals starting with 04 and onward.

**Comment by swails** [comment]
> I did sleep - there is a gap of 6-7 hours between my two comments :)

haha.  My hat is off to you, sir.

> Are you sure you'd rather use 9 over 10? 10 is a bit closer to what we might do in a "production" environment.

The only difference that I can tell is the use of a switch, right?  In any case, I already test that the switch is properly turned on elsewhere in the test suite (and different programs may use different switching functions, etc.)  No switch is a simpler functional form (and Amber doesn't support vdW switching, either) that is marginally faster to evaluate.

> Also, I don't think 03 contains any improper dihedrals; I built that system by hand some time ago and I don't think it's a correct reproduction of the AMBER force field. I only have improper dihedrals starting with 04 and onward.

Good to know.  I liked that 03 was separate molecules, though, and is a more complex code path than a single-molecule system.  If the DHFR tests have impropers (which they _must_, right?) then I think we have that path covered as well.  I'll go ahead and add 04 as well -- as you mentioned, these tiny systems take seconds to execute, at most.

**Comment by leeping** [comment]
Yeah, everything before 06 takes just a few seconds. :)

**Comment by swails** [comment]
In the 09 test, it looks like you set the PME order in Gromacs to 5, but OpenMM only supports 4.  Is this intentional, or am I misreading something?

**Comment by leeping** [comment]
I was basing that off one of Peter's forum posts, but I didn't double-check with the source code:

https://simtk.org/forums/viewtopic.php?f=161&t=5556&start=20#p13997

**Comment by swails** [comment]
So it is!  That's what I get for assuming.

**Comment by swails** [comment]
(P.S., I did just check the source code, and that appears to be true on all platforms)

**Comment by leeping** [comment]
That's great. :)  I'll also look at your modifications to my scripts so I can make ForceBalance Gromacs-5 compatible.

**Comment by swails** [comment]
I don't think it'll be too hard

**Comment by leeping** [comment]
Okay, things are working here with both Gromacs 4 and 5, and it uses double precision Gromacs if available.

Thanks,
- Lee-Ping

**Comment by leeping** [comment]
Hi Jason,

In order to get the output AMBER `prmtop` to work, I suggested some changes outside of the Gromacs module.  The first change was that sander needed virtual site atom types to be named `'EP'`.  

In `chemistry/amberparm/_amberparm.py`:

```
@@ -1459,6 +1461,9 @@ class AmberParm(AmberFormat, Structure):
             data['SCREEN'] = [atom.screen for atom in self.atoms]
         if 'ATOMIC_NUMBER' in data:
             data['ATOMIC_NUMBER'] = [atom.atomic_number for atom in self.atoms]
+            for iatom, atom in enumerate(self.atoms):
+                if atom.atomic_number == 0:
+                    data['AMBER_ATOM_TYPE'][iatom] = 'EP'
         # Do the non-bonded exclusions now
         data['EXCLUDED_ATOMS_LIST'] = []
         nextra = 0
```

The second change was that dihedral types weren't being correctly assigned when the list was split.  I implemented a different mapping from the old (un-split) dihedral types to the new dihedral types which I think solves the problem.

In `chemistry/structure.py`:

```
@@ -447,11 +447,17 @@ class Structure(object):
             c.angle_types.append(copy(at))
         c.angle_types.claim()
         if split_dihedrals:
-            for dt in self.dihedral_types:
+            ndt = 0
+            mapdt = {}
+            for idt, dt in enumerate(self.dihedral_types):
                 if hasattr(dt, '__iter__'):
                     for t in dt:
                         c.dihedral_types.append(copy(t))
+                        mapdt.setdefault(idt, []).append(ndt)
+                        ndt += 1
                 else:
+                    mapdt.setdefault(idt, []).append(ndt)
+                    ndt += 1
                     c.dihedral_types.append(copy(dt))
         else:
             for dt in self.dihedral_types:
@@ -507,7 +513,7 @@ class Structure(object):
                 if hasattr(d.type, '__iter__'):
                     for i in range(len(d.type)):
                         ie = d.ignore_end or i < len(d.type) - 1
-                        ti = d.type.idx + i
+                        ti = mapdt[d.type.idx][i]
                         c.dihedrals.append(
                                 Dihedral(c.atoms[d.atom1.idx],
                                          c.atoms[d.atom2.idx],
```

I think improper dihedrals are the next thing to tackle.

Thanks,
- Lee-Ping

**Comment by swails** [comment]
Sorry!  I didn't realize you had added everything into this branch.  Ultimately I'd rather not track `GmxTests` which is why I haven't merged this yet.  But since it will clearly help track down these issues, I'll go ahead and merge it so I can help out.

**Comment by leeping** [comment]
Actually, it's cool if you don't merge it. :)  I was mainly using this just as a discussion thread and to keep track of my own work.

**Comment by swails** [comment]
Yes, but you were putting fixes into this branch as well :).  And I've already merged it into my working tree on my machine, so I'll stick with it.

And it will let me help in debugging issues.

BTW, off-topic, I saw that you're on the invitee/speaker list for the Amoeba Telluride meeting.  Awesome!  I hope to see you there!

**Comment by swails** [comment]
Hey -- something you might be interested in.  I wrote a Python (and C, C++, and Fortran) API into sander.  So to get energies and forces from sander, it's as easy as doing something like this:

``` Python
import chemistry as chem
import sander
nonper_inp = sander.gas_input() # You can set a GB model if you want
pme_inp = sander.pme_input()
pme_inp.cut = 9 # Angstroms
parm = chem.amber.AmberParm('my_prmtop.parm7', 'my_inpcrd.rst7') # get an AmberParm *somehow*

with sander.setup(parm, parm.coords, parm.box, pme_inp):
    for crd in traj:
        sander.set_positions(crd)
        ene, frc = sander.energy_forces()
```

Energies are in a struct (should've been a dict, but it's basically the same thing) and frc is an array; units are AKMA (kcal/mol and kcal/mol/Angstrom).

**Comment by swails** [comment]
I was thinking about putting a Linux and Mac build of pysander up on conda.  Would you find that useful?

**Comment by leeping** [comment]
Yeah, they made me a chair / speaker for the Telluride meeting; I have no idea what I'll be doing. :D  But I look forward to seeing you there!

I think pysander sounds incredibly helpful. :)  I haven't used conda before; I habitually build stuff from source, but it would be fun to try the installer.

**Comment by swails** [comment]
You can certainly build it from source, but AmberTools 15 inserts its own ParmEd packages into your `PYTHONPATH` that could conflict with whatever you're trying from Github.

The way around it is to `python setup.py install --prefix=$AMBERHOME` to override the Amber ParmEd installed files with the ones from github.

**Comment by leeping** [comment]
Sounds good.  I've sent another PR: https://github.com/swails/ParmEd/pull/7

**Pull request merged**
